#  Makefile
#
#  Filename:  $Source: /cvshome/crd/xlr8/src/bin/web/content/js/page/Makefile,v $
#  Revision:  $Revision: 1.7 $
#  Date:      $Date: 2009-04-15 20:38:13 $
#  Author:    $Author: berry $
# 
#  (C) Copyright 2002-2005 Tall Maple Systems, Inc.  
#  All rights reserved.
#

include ${PROD_TREE_ROOT}/src/mk/common.mk

FILES_INSTALL_DIR=/lib/web/content/js/page

FILES= \
	MemcacheService.js			\
	MemcacheService.server.js	\
	memcache-services.js 		\
	memcache-stats.js 			\
	appliance-media.js 			\
	appliance-status.js 		\



include ${PROD_TREE_ROOT}/src/mk/files.mk

