#  Makefile
#
#  Filename:  $Source: /cvshome/crd/xlr8/src/bin/statsproxy/html/images/Makefile,v $
#  Revision:  $Revision: 1.7 $
#  Date:      $Date: 2010-03-10 21:29:47 $
#  Author:    $Author: berry $
# 
#  (C) Copyright 2002-2005 Tall Maple Systems, Inc.  
#  All rights reserved.
#

include ${PROD_TREE_ROOT}/src/mk/common.mk

FILES_INSTALL_DIR=/lib/web/content/statsproxy/images

FILES= \
	chart_icon.gif		\
	check.gif		\
	down_arrow.gif		\
	down_arrow_white.gif	\
	logo-color-off.png	\
	logo.png		\
	logo.gif		\
	range_end_thumb.gif \
	range_start_thumb.gif \
	round_close_green.png \
	round_close_red.png \
	round_close_white.png \
	selected_view_indicator.gif \
	tab_scroll_left.png \
	tab_scroll_right.png \
	table_icon.gif		\
	window_arrow_collapsed.gif \
	window_arrow_collapsed_white.gif \
	window_arrow_expanded.gif \
	window_arrow_expanded_white.gif \


SUBDIRS= \
	famfamfam	\
	honeycomb	\

include ${PROD_TREE_ROOT}/src/mk/files.mk
