#  Makefile
#
#  Filename:  $Source: /cvshome/crd/xlr8/src/bin/statsproxy/html/Makefile,v $
#  Revision:  $Revision: 1.3 $
#  Date:      $Date: 2010-03-22 23:54:03 $
#  Author:    $Author: berry $
# 
#  (C) Copyright 2002-2005 Tall Maple Systems, Inc.  
#  All rights reserved.
#

include ${PROD_TREE_ROOT}/src/mk/common.mk

FILES_INSTALL_DIR=/lib/web/content/statsproxy

FILES = 			\
	index.html 		\
	statsproxy.css 	        \
	acknowledgements.html   \
	clippy.swf

SUBDIRS=	\
	images 	\
	js 	\
	lang 	\


include ${PROD_TREE_ROOT}/src/mk/files.mk
