#  Makefile
#
#  Filename:  $Source: /cvshome/crd/xlr8/src/bin/web/content/js/Gear6/Makefile,v $
#  Revision:  $Revision: 1.6 $
#  Date:      $Date: 2009-11-10 02:00:30 $
#  Author:    $Author: berry $
# 
#  (C) Copyright 2002-2005 Tall Maple Systems, Inc.  
#  All rights reserved.
#

include ${PROD_TREE_ROOT}/src/mk/common.mk

FILES_INSTALL_DIR=/lib/web/content/js/Gear6

FILES= \
	Page.js                   \
	Module.js                 \
	MemcacheService.editor.js \
	User.editor.js			  \
	User.password.js		  \
	MemcacheInstance.js       \
	MemcacheService.js        \
	ModuleBay.js              \
	UserTable.js			  \
	User.js		    		  \
	config.js                 \
	Recipient.editor.js		  \
	Recipient.js			  \
	RecipientTable.js		  \
	ServiceTreeSelector.js	  \
	StatsCollector.js		  \



SUBDIRS=  \
	appliance-media     \
	appliance-status    \
	memcache            \
	memcache-allocation \
	memcache-stats      \
	users               \
	recipients          \


include ${PROD_TREE_ROOT}/src/mk/files.mk

