#  Makefile
#
#  Filename:  $Source: /cvshome/crd/xlr8/src/bin/statsproxy/html/js/flot/Makefile,v $
#  Revision:  $Revision: 1.2 $
#  Date:      $Date: 2010-01-15 01:28:48 $
#  Author:    $Author: berry $
# 
#  (C) Copyright 2002-2005 Tall Maple Systems, Inc.  
#  All rights reserved.
#

include ${PROD_TREE_ROOT}/src/mk/common.mk

FILES_INSTALL_DIR=/lib/web/content/statsproxy/js/flot

FILES= \
	excanvas.js	\
	excanvas.min.js	\
	jquery.colorhelpers.js	\
	jquery.colorhelpers.min.js	\
	jquery.flot.crosshair.js	\
	jquery.flot.crosshair.min.js	\
	jquery.flot.image.js	\
	jquery.flot.image.min.js	\
	jquery.flot.js	\
	jquery.flot.min.js	\
	jquery.flot.navigate.js	\
	jquery.flot.navigate.min.js	\
	jquery.flot.selection.js	\
	jquery.flot.selection.min.js	\
	jquery.flot.stack-mod.js	\
	jquery.flot.stack-mod.min.js	\
	jquery.flot.stack.js	\
	jquery.flot.stack.min.js	\
	jquery.flot.threshold.js	\
	jquery.flot.threshold.min.js	\
	jquery.js	\
	jquery.min.js	\


include ${PROD_TREE_ROOT}/src/mk/files.mk
