#  Makefile
#
#  Filename:  $Source: /cvshome/crd/xlr8/src/bin/statsproxy/html/lang/Makefile,v $
#  Revision:  $Revision: 1.1 $
#  Date:      $Date: 2009-07-24 17:59:49 $
#  Author:    $Author: berry $
# 
#  (C) Copyright 2002-2005 Tall Maple Systems, Inc.  
#  All rights reserved.
#

include ${PROD_TREE_ROOT}/src/mk/common.mk

FILES_INSTALL_DIR=/lib/web/content/statsproxy/lang

FILES= \
	messages.en.txt	\


include ${PROD_TREE_ROOT}/src/mk/files.mk
