#  Makefile
#
#  Filename:  $Source: /cvshome/crd/xlr8/src/bin/statsproxy/html/js/Makefile,v $
#  Revision:  $Revision: 1.6 $
#  Date:      $Date: 2010-02-23 23:51:50 $
#  Author:    $Author: berry $
# 
#  (C) Copyright 2002-2005 Tall Maple Systems, Inc.  
#  All rights reserved.
#

include ${PROD_TREE_ROOT}/src/mk/common.mk

FILES_INSTALL_DIR=/lib/web/content/statsproxy/js

FILES= \
	history.js		\
	jquery.ba-bbq.js	\
	jquery.ba-bbq.min.js	\
	jquery.js		\
	jquery.base64-mod.js \
	lib.js			\
	api.js			\
	serviceView.js		\
	statsproxy-views.js	\
	statsproxy-api.js	\
	statsproxy.js		\
	types.js		\
	widgets.js		\
	md5.js


SUBDIRS=	\
	flot

include ${PROD_TREE_ROOT}/src/mk/files.mk
