#  Makefile
#
#  Filename:  $Source: /cvshome/crd/xlr8/src/bin/statsproxy/html/images/famfamfam/Makefile,v $
#  Revision:  $Revision: 1.1 $
#  Date:      $Date: 2010-01-15 01:28:51 $
#  Author:    $Author: berry $
# 
#  (C) Copyright 2002-2005 Tall Maple Systems, Inc.  
#  All rights reserved.
#

include ${PROD_TREE_ROOT}/src/mk/common.mk

FILES_INSTALL_DIR=/lib/web/content/statsproxy/images/famfamfam

FILES= \
	accept.png	\
	add.png	\
	arrow_redo.png	\
	arrow_undo.png	\
	bullet_blue.png	\
	bullet_green.png	\
	bullet_orange.png	\
	bullet_pink.png	\
	bullet_purple.png	\
	bullet_red.png	\
	bullet_white.png	\
	bullet_yellow.png	\
	cancel.png	\
	cross.png	\
	delete.png	\
	drive.png	\
	drive_add.png	\
	drive_delete.png	\
	drive_error.png	\
	error.png	\
	exclamation.png	\
	help.png	\
	information.png	\
	lock.png	\
	lock_open.png	\
	magnifier.png	\
	note.png	\
	pencil.png	\
	printer.png	\
	readme.txt	\
	server.png	\
	server_add.png	\
	server_edit.png	\
	server_error.png	\
	server_go.png	\
	star.png	\
	tick.png	\
	time.png	\


include ${PROD_TREE_ROOT}/src/mk/files.mk
