#  Makefile
#
#  Filename:  $Source: /cvshome/crd/xlr8/src/bin/web/content/js/Gear6/memcache-stats/Makefile,v $
#  Revision:  $Revision: 1.1 $
#  Date:      $Date: 2009-06-01 22:13:12 $
#  Author:    $Author: berry $
# 
#  (C) Copyright 2002-2005 Tall Maple Systems, Inc.  
#  All rights reserved.
#

include ${PROD_TREE_ROOT}/src/mk/common.mk

FILES_INSTALL_DIR=/lib/web/content/js/Gear6/memcache-stats

FILES= \
	page.js      \



include ${PROD_TREE_ROOT}/src/mk/files.mk
